### ISSUE TITLE
Use Ruff instead of Pydocstsyle for docstring checking

### ISSUE THREAD

**Issue by scott-huberty** [mscheltienne/template-python#58]
Hi @mscheltienne thank you for this gem*. 

I am wondering, since [PyDocstyle has been publicly archived](https://github.com/PyCQA/pydocstyle), if this template should instead use [ruff.lint.pydocstyle](https://docs.astral.sh/ruff/settings/#lintpydocstyle) (which is what the PyDocstyle devs recommend)?

I've already configured one of my repositories built on this template to do just that. So if you are open to it, I can submit a quick PR.

_________________

*If this package is meant for your personal use-cases and not for general consumption, then feel free to close this.

**Comment by mscheltienne** [comment]
Feel free to open a PR! I'd love to get rid of some. tooling in favor of ruff!

**Comment by scott-huberty** [comment]
incoming!
